blog/urls.py
from django.urls import path,include
from . import views

urlpatterns = [
    path('',views.index),
    path('<slug:pk>/',views.article)
]

config/urls.py
from django.contrib import admin
from django.urls import path,include
from mainapp import views
from django.conf import settings
from django.conf.urls.static import static


handler500 = views.my_customized_server_error

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('mainapp.urls')),
    path('blog/',include('blog.urls')),
    path('store/',include('store.urls',namespace='store')),
    path('basket/',include('basket.urls',namespace='basket')),
    path('payment/',include('payment.urls',namespace='payment')),
    path('orders/',include('orders.urls',namespace='orders')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)

mainapp/urls.py
from django.urls import path,include
from . import views
from django.contrib import admin
from django.urls import path,include
from mainapp import views
from django.contrib.auth.views import LogoutView
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView

from mainapp.forms import (PwdResetConfirmForm, PwdResetForm)

app_name = 'mainapp'

urlpatterns = [
    path('',views.index),
    path('login/', views.Login.as_view()),
    path('logout/', LogoutView.as_view()),
    path('signup/', views.signup),
    path('activate/<slug:uidb64>/<slug:token>', views.activate,name='activate'),
    #reset password
    path('password_reset/', auth_views.PasswordResetView.as_view(template_name="mainapp/user/password_reset_form.html",
                                                                 success_url='password_reset_email_confirm',
                                                                 email_template_name='mainapp/user/password_reset_email.html',
                                                                 form_class=PwdResetForm), name='pwdreset'),
    path('password_reset_confirm/<uidb64>/<token>', auth_views.PasswordResetConfirmView.as_view(template_name='mainapp/user/password_reset_confirm.html',
                                                                                                success_url='/password_reset_complete', 
                                                                                                form_class=PwdResetConfirmForm),
         name="password_reset_confirm"),
    path('password_reset/password_reset_email_confirm/',
         TemplateView.as_view(template_name="mainapp/user/reset_status.html"), name='password_reset_done'),
    path('password_reset_complete/',
         TemplateView.as_view(template_name="mainapp/user/reset_status.html"), name='password_reset_complete'),
    path('delete_user/',views.delete_user, name='delete_user'),
    path('delete_confirmation/',views.delete_confirmation,name='delete_confirmation'),
    path('delete_cancel/',views.delete_cancel,name='delete_cancel'),
    path('account/', views.account, name='account'),
    path('account_update/', views.account_update, name='account_update'),
    path('dashboard/',views.dashboard,name='dashboard'),
    path('contact/', views.contact,name='contact'),
    path('privacy/', views.privacy,name='privacy'),
    path('quotation/', views.quotation, name='quotation'),

]

blog/models.py
from django.db import models
from django.contrib.auth import get_user_model

# Create your models here.
class Article(models.Model):
    title = models.CharField(default="", max_length=30)
    text = models.TextField(default="",)
    author = models.CharField(default="", max_length=30)
    created_at = models.DateField(auto_now_add=True)
    updated_at = models.DateField(auto_now=True)

class Comment(models.Model):
    comment = models.TextField(default="", max_length=500)
    created_at = models.DateField(auto_now_add=True)
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE, related_name='author')

mainapp/models/account_models.py
from django.db import models
from django.contrib.auth.models import BaseUserManager

from django.contrib.auth import get_user_model
from django.core.mail import send_mail
import os



class UserManager(BaseUserManager):
    def create_user(self,email,password=None):
        if not email:
            raise ValueError('Users must have an email address')
        user = self.model(
            email=self.normalize_email(email),
        )
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self,email,password=None):
        user = self.create_user(
            email,
            password=password
        )
        user.is_admin = True
        user.is_active = True
        user.save(using=self._db)
        return user
    

mainapp/models/profile_models.py
from django.db import models
from django.contrib.auth import get_user_model

class Profile(models.Model):
    user = models.OneToOneField(get_user_model(),unique=True, on_delete=models.CASCADE, primary_key=True)
    username = models.CharField(default="",max_length=30)
    zipcode = models.CharField(default="",max_length=8)
    prefecture = models.CharField(default="",max_length=6)
    city = models.CharField(default="",max_length=100)
    address1 = models.CharField(default="",max_length=200)
    address2 = models.CharField(default="",max_length=50,null=True)
    stripe_id= models.CharField(default="",max_length=30,null=True)
    

mainapp/models/user_models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser
from .account_models import UserManager
from django.core.mail import send_mail
import os

class User(AbstractBaseUser):
    email = models.EmailField(max_length=255,unique=True)
    
    is_active = models.BooleanField(default=False)
    is_admin = models.BooleanField(default=False)
    objects = UserManager()
    
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []
    
    def __str__(self):
        return self.email
    
    def has_perm(self, prerm, obj=None):
        "Does the user have a specific permission?"
        return True
    
    def has_module_perms(self, app_label):
        "Does the user have permissions to view the app 'app_label'?"
        return True
    
    def email_user(self, subject, message):
        email_from = os.environ['EMAIL_HOST_USER']
        email_to = [self.email]
        send_mail(
            subject,
            message,
            email_from,
            email_to,
            fail_silently=False,
        )
    
    @property
    def is_staff(self):
        "Is the user a member of staff?"
        return self.is_admin
    
from django.db.models.signals import post_save
from django.dispatch import receiver

@receiver(post_save, sender=User)
def create_onetoone(sender, **kwargs):
    if kwargs['created']:
        from mainapp.models.profile_models import Profile
        
        Profile.objects.create(user=kwargs['instance'])

quotation/models.py
from django.db import models

# Create your models here.

mainapp/forms.py
from django import forms
from django.contrib.auth.forms import (PasswordResetForm,SetPasswordForm)
from django.contrib.auth import get_user_model
from .models.profile_models import Profile
from .models.user_models import User

class UserCreationForm(forms.ModelForm):
    password = forms.CharField()
    
    class Meta:
        model = get_user_model()
        fields = ('email',)
        
    def clean_password(self):
        password =self.cleaned_data.get("password")
        return password
    
    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password"])
        if commit:
            user.save()
        return user
    
class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = (
            'username',
            'zipcode',
            'prefecture',
            'city',
            'address1',
            
            
        )
        
class PwdResetForm(PasswordResetForm):

    email = forms.EmailField(max_length=254, widget=forms.TextInput(
        attrs={'class': 'form-control mb-3', 'placeholder': 'Email', 'id': 'form-email'}))

    def clean_email(self):
        email = self.cleaned_data['email']
        u = User.objects.filter(email=email)
        if not u:
            raise forms.ValidationError(
                'そのE-mailアドレスは登録されていません。')
        return email


class PwdResetConfirmForm(SetPasswordForm):
    new_password1 = forms.CharField(
        label='新しいパスワード', widget=forms.PasswordInput(
            attrs={'class': 'form-control mb-3', 'placeholder': 'New Password', 'id': 'form-newpass'}))
    new_password2 = forms.CharField(
        label='もう一度入力してください。', widget=forms.PasswordInput(
            attrs={'class': 'form-control mb-3', 'placeholder': 'New Password', 'id': 'form-new-pass2'}))
        

blog/views.py
from django.shortcuts import render
from django.http import HttpResponse
from blog.models import Article
from django.core.paginator import Paginator
# Create your views here.




def index(request):
    objs = Article.objects.all()
    paginator = Paginator(objs, 2)
    page_number = request.GET.get('page')
    page_range = paginator.page_range
    context = {
        'page_obj': paginator.get_page(page_number),
        'page_number': page_number,
        'page_range': page_range,
    }
    return render(request, 'blog/blogs.html', context)

def article(request, pk):
    obj = Article.objects.get(pk=pk)
    context = {
        'pk':pk,
        'article':obj,
    }
    return render(request, 'blog/article.html', context)

mainapp/views.py
from django.shortcuts import render,redirect
from blog.models import Article
from django.contrib.auth.views import LoginView
from django.views.decorators.csrf import csrf_exempt
from django.http import  HttpResponse, JsonResponse
from django.contrib.sites.shortcuts import get_current_site
from django.template.loader import render_to_string
from django.utils.encoding import force_bytes, force_str
from django.utils.http import urlsafe_base64_decode, urlsafe_base64_encode

from .tokens import account_activation_token
from .models.user_models import User
from .models.profile_models import Profile
from mainapp.forms import UserCreationForm, ProfileForm
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth import login,logout
from django.core.mail import send_mail
from orders.views import user_orders

import os


def index(request):
    objs=Article.objects.all()
    context={
        'articles': objs
    }
    return render(request,'mainapp/index.html',context)

def signup(request):
    context={}
    if request.user.is_authenticated:
        return redirect('/')
    if request.method == 'post':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            #user.is_active = False
            user.save()
            # login(request,user)
            # messages.success(request,"登録完了！")
            current_site = get_current_site(request)
            subject = 'Tuttofareアカウントをアクティベートしてください'
            message = render_to_string('mainapp/registration/account_activation_email.html', {
                'user': user,
                'domain': current_site.domain,
                'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                'token': account_activation_token.make_token(user),
            })
            user.email_user(subject=subject, message=message)
            my_text = '新規登録が成功しました。\nアクティベーション用のリンクをご登録メールにお送りしました。\
                \n（迷惑メールフォルダに入っている可能性があります。）\
                \nregistered succesfully and activation sent'
            return HttpResponse(my_text.encode('Shift_JIS'),content_type='text/plain')
        else:
            context = {'form':form}
    return render(request,'mainapp/auth.html',context)

def activate(request,uidb64,token):
    try:
        uid = force_str(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except:
        print('uid, userが見つかりません。')
    if user is not None and account_activation_token.check_token(user,token):
        user.is_active = True
        user.save()
        login(request,user)
        return redirect('/')
    else:
        return render(request,'mainapp/registration/activation_invalid.html')
    
      
    

class Login(LoginView):
    template_name = 'mainapp/auth.html'

    def form_valid(self,form):
        messages.success(self.request, "ログイン完了！")
        return super().form_valid(form)

    def form_invalid(self, form):
        messages.error(self.request, "ログイン失敗！")
        return super().form_invalid(form)

# def logout(request):
#     context={}
#     return render(request,'mainapp/logout.html',context)

@login_required
def dashboard(request):
    context={}
    try:
        orders = user_orders(request)
        context['orders']=orders
    except:
        print('no orders')
    
   
    return render(request,'mainapp/dashboard.html',context)

@login_required
def account(request):
    print(request.user)
    profile=Profile.objects.get(user=request.user)
    
    
    if request.method == 'POST':
        form = ProfileForm(request.POST)
        print(form)
        if form.is_valid():
            profile = form.save(commit=False)
            profile.user = request.user
            profile.save()
            messages.success(request,"アカウント情報更新完了！")
            context={'profile':profile}
            return render(request,'mainapp/account.html',context)
    context={'profile':profile}
    return render(request,'mainapp/account.html',context)

@login_required
def account_update(request):
   
    print("username",request.POST.get('username'))
    user=User.objects.get(id=request.POST.get('key'))
    
    defaults={
            'username':request.POST.get('username'),
            'prefecture':request.POST.get('prefecture'),
            'city':request.POST.get('city'),
            'address1':request.POST.get('address1'),
            'address2':request.POST.get('address2'),
            'zipcode':request.POST.get('zipcode')}
    try:
        obj = Profile.objects.get(user=user)
      
        for key, value in defaults.items():
            setattr(obj, key, value)
        obj.user = user
        obj.save()
    except Profile.DoesNotExist:
        new_values = {'user': user}
        new_values.update(defaults)
        obj = Profile(**new_values)
        obj.save()
    context = {'msg':'アカウント更新完了！','profile':defaults}
    return JsonResponse((context))
    # if created:
    #     messages.success(request,"アカウント情報更新完了！")
    #     context={'message':'更新完了', 'profile':profile}
    #     return JsonResponse((context))
    

@login_required
def delete_user(request):
    context={'email':request.user.email}
    # if request.method == 'POST':
    #     redirect_url = reverse('mainapp:delete_confirmation')
    #     email=request.user.email
        
    #     params=urlencode({'email':email})
    #     url=f'{redirect_url}?{params}'
    #     return redirect(url)
    return render(request,'mainapp/user/delete_confirmation.html',context)

@login_required
def delete_confirmation(request):
    if request.method == 'POST':
        email=request.POST.get('email')
        print(email)
        user = User.objects.get(email=email)
        if user is not None:
            
            user.is_active=False
            user.delete()
            logout(request)
            
            my_text = f'{email}様のアカウントは削除されました。\nご利用いただきありがとうございました。'
            return HttpResponse(my_text.encode('Shift_JIS'),content_type='text/plain')
    
    

def delete_cancel(request):
    email = request.GET.get('email')
    return redirect('/account')

def contact(request):
    context = {}
    if request.method == 'POST':
        subject = "お問い合わせがありました。"
        message = "お問い合わせがありました。\n名前: {}\nメールアドレス: {}\n内容: {}".format(
                    request.POST.get('name'),
                    request.POST.get('email'),
                    request.POST.get('content'))        
        
        email_from = os.environ['EMAIL_HOST_USER']
        email_to = [
        os.environ['EMAIL_HOST_USER'], 
        ]
        send_mail(subject,message, email_from,email_to)
        messages.success(request,'お問い合わせいただきありがとうございました。ご入力内容が送信されました。')
    return render(request,'mainapp/contact.html',context)


def privacy(request):
    context={}
    return render(request, 'mainapp/privacy.html',context)

@csrf_exempt
def quotation(request):
    context={}
    return render(request,'mainapp/quotation.html',context)

def success(request):
    user = User.objects.get(id=request.user.id)
    context={"username": user.email}
    return render(request,'mainapp/success.html',context)

def cancel(request):
    context={}
    return render(request,'mainapp/cancel.html',context)






from django.views.decorators.csrf import requires_csrf_token
from django.http import HttpResponseServerError

@requires_csrf_token
def my_customized_server_error(request, template_name='500.html'):
    import sys
    from django.views import debug
    error_html = debug.technical_500_response(request, *sys.exc_info()).content
    return HttpResponseServerError(error_html)

quotation/views.py
from django.shortcuts import render

# Create your views here.

templates/mainapp/account.html
{% extends 'mainapp/base_index.html' %} {%block content%}{% load static %}
<div class="page-top"></div>
<div class="container">
  {% for message in messages %}
  <div {% if message.tags %}class="{{ message.tags }}" {% endif %}>
    {{ message }}
  </div>

  {% endfor %}

  <h1 class="page-title">アカウントページ</h1>


  <form class="row g-3 pt-4" method="POST" action="{%url 'mainapp:account'%}">
    {% csrf_token %}
    <div class="col-md-8 col-sm-12">
      <label class="form-label">ユーザー名</label>
      <input type="text" class="form-control" id="id_username" name="username" placeholder="ユーザ名"
        value="{{ profile.username }}">
    </div>

    <div class="col-md-6">
      <label class="form-label">郵便番号(住所が自動入力されます。）</label>
      <input type="text" class="form-control" id="zipcode" name="zipcode" value="{{ profile.zipcode}}">
    </div>
    <div class="col-md-3 d-grid ">
      <label class="form-label">住所→郵便番号</label>
      <button class="btn btn-custom" id="search" type="button">郵便番号検索</button>
      <p id="error"></p>
    </div>
    <div class="col-md-3">
      <label class="form-label">都道府県</label>
      <input type="hidden" id="address1" name="address1" value="{{ profile.prefecture}}" placeholder="例）大阪府">
      <select class="form-control" name="prefecture" id="pref_name">
        <option value="" selected>選択してください</option>
        <option value="北海道">北海道</option>
        <option value="青森県">青森県</option>
        <option value="岩手県">岩手県</option>
        <option value="宮城県">宮城県</option>
        <option value="秋田県">秋田県</option>
        <option value="山形県">山形県</option>
        <option value="福島県">福島県</option>
        <option value="茨城県">茨城県</option>
        <option value="栃木県">栃木県</option>
        <option value="群馬県">群馬県</option>
        <option value="埼玉県">埼玉県</option>
        <option value="千葉県">千葉県</option>
        <option value="東京都">東京都</option>
        <option value="神奈川県">神奈川県</option>
        <option value="新潟県">新潟県</option>
        <option value="富山県">富山県</option>
        <option value="石川県">石川県</option>
        <option value="福井県">福井県</option>
        <option value="山梨県">山梨県</option>
        <option value="長野県">長野県</option>
        <option value="岐阜県">岐阜県</option>
        <option value="静岡県">静岡県</option>
        <option value="愛知県">愛知県</option>
        <option value="三重県">三重県</option>
        <option value="滋賀県">滋賀県</option>
        <option value="京都府">京都府</option>
        <option value="大阪府">大阪府</option>
        <option value="兵庫県">兵庫県</option>
        <option value="奈良県">奈良県</option>
        <option value="和歌山県">和歌山県</option>
        <option value="鳥取県">鳥取県</option>
        <option value="島根県">島根県</option>
        <option value="岡山県">岡山県</option>
        <option value="広島県">広島県</option>
        <option value="山口県">山口県</option>
        <option value="徳島県">徳島県</option>
        <option value="香川県">香川県</option>
        <option value="愛媛県">愛媛県</option>
        <option value="高知県">高知県</option>
        <option value="福岡県">福岡県</option>
        <option value="佐賀県">佐賀県</option>
        <option value="長崎県">長崎県</option>
        <option value="熊本県">熊本県</option>
        <option value="大分県">大分県</option>
        <option value="宮崎県">宮崎県</option>
        <option value="鹿児島県">鹿児島県</option>
        <option value="沖縄県">沖縄県</option>
      </select>
    </div>
    <div class="col-md-6">
      <label class="form-label">市区町村</label>
      <input type="text" class="form-control" id="address2" name="city" value="{{ profile.city}}">
    </div>

    <div class="col-12">
      <label class="form-label">町域</label>
      <input type="text" class="form-control" id="address3" name="address1" placeholder=""
        value="{{ profile.address1}}">
    </div>
    <div class="col-12">
      <label class="form-label">建物名等</label>
      <input type="text" class="form-control" id="address4" name="address2" placeholder=""
        value="{{ profile.address2}}">
    </div>

    <div class="col-md-12 d-grid">
      <button type="submit" class="btn btn-info btn-block fw-bold w-100">保存</button>
    </div>
    <hr />
  </form>
  <p class="pt-4 font-weight-bold">退会する</p>


  <p>アカウントを削除しますがよろしいですか？</p>
  <div class="col-md-3 d-grid">
    <a type="button" role="button" class="btn btn-danger btn-block  mb-4 fw-bold w-100"
      href="{%url 'mainapp:delete_user'%}">退会する</a>
  </div>






  {% include 'mainapp/snippets/sidebar.html' %}

</div>
<script src="{% static 'mainapp/js/search_address.js'%}"></script>

{%endblock%}

templates/mainapp/auth2.html
{% extends 'mainapp/base_auth.html' %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-lg-3 m-auto">
            <h1 class="display-4 font-italic text-center"><a href="/" 
            class="text-decoration-none">トットファーレ</a></h1>
        </div>
        <div class="col-lg-3 m-auto">

            <form class="form-signin mx-4" method="POST">
              {% csrf_token %}
                <div class="text-center">
                    <h1 class="h5 my-4">
                      {% if 'login' in request.path %}
                      ログイン
                      {% elif 'signup'%}
                      新規登録
                      {% endif %}
                    </h1>
                </div>

                <div class="form-label-group my-3">
                    <input type="email" id="id_email" name="{% if 'login' in request.path %}username{% elif 'signup' %}email{%endif%}" class="form-control"
                    placeholder="Email address" required autofocus>
                </div>

                <div class="form-label-group my-3">
                    <input type="password" id="id_password" name="password" class="form-control"
                    placeholder="Password" required>
                </div>
                
                <button class="btn btn-primary btn-block m-auto" type="submit">
                    {% if 'login' in request.path %} 
                      ログイン
                    {% elif 'signup' %}
                      新規登録
                    {% endif %}
                </button>
            
                
            </form>

            {% if 'login' in request.path %}
            <div class="text-center">
                <a href="/signup/" class="link-secondary">新規登録はこちら</a>
            </div>
            {% elif 'signup' in request.path %}
            <div class="text-center">
                <a href="/login/" class="link-secondary">ログインはこちら</a>
            </div>
            {% endif %}
        </div>
    </div>
</div>
{% endblock content %}

templates/mainapp/base_auth.html
<!doctype html>
<html lang="ja">

{% load static %}

<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="description" content="" />
  <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors" />
  <meta name="generator" content="Hugo 0.83.1" />
  <meta name="description" content="A demo of a payment on Stripe" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>Tottofare</title>

  <!--
   <link rel="canonical" href="https://getbootstrap.jp/docs/5.0/examples/navbar-static/" />
  -->
  <script src="https://js.stripe.com/v3/"></script>


  <!-- Bootstrap core CSS -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous" />
  <link href="https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css" rel="stylesheet" />

  <!-- Custom styles for this template -->
  <link href="{% static 'mainapp/styles/style.css' %}" rel="stylesheet" />
  <script src="https://kit.fontawesome.com/71c00e5ffa.js" crossorigin="anonymous"></script>
</head>

<body class="ink-grid">

  {% block content %}
  {% include 'mainapp/snippets/messages.html' %}
  {% endblock content %}
</body>

</html>

templates/mainapp/create_post.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <div class="form-signin">
        <h1 class="h3 mb-3 fw-normal">Welcome to {{current_user.username}}'s blog post page. Please post it!</h1>
        <form class="form-group" method="POST">
            {{form.hidden_tag()}}
            <div class="form-group">
                {{form.title.label(class="form-control-label")}}
                {{form.title(class="form-control form-control-lg")}}
            </div>
            <div class="form-group">
                {{form.text.label(class="form-control-label")}}
                {{form.text(class="form-control form-control-lg ")}}
            </div>
            <br>
            <div class="form-group">
                {{form.submit(class="btn btn-outline-info")}}
            </div>
        </form>

    </div>
</div>

{% endblock %}

templates/mainapp/dashboard.html
{% extends "mainapp/base_index.html" %} {% load static %}{%load humanize%} {% block content %}

<div class="page-top"></div>
<div class="container" style="max-width: 1000px">
    <div class="flex align-items-center dashboard-title my-3 py-3">
        <h1 class="page-top-title">ダッシュボード</h1>
        <div class="px-5 text-white"><b>注文の管理</b> と<b>アカウント情報</b>の管理に利用してください。</div>

    </div>
    <div class="col-12 ">
        <a type='button' class="btn btn-dashboard" href="{% url  'mainapp:account' %}">
            <i class='bx bxs-user-account iconarea'></i>
            <span class="ms-5">アカウント情報</span>
        </a>

    </div>
    <hr />
</div>
<div class="container" style="max-width: 1000px">
    {% for order in orders %}
    <div class="row g-3">

        <div class="col-12 bg-light p-3 d-flex justify-content-between">
            <div class="d-flex d-flex-inline">

                <div class="pe-3">{{ order.created }}</div>
                <div class="dropdown">
                    <a class="text-reset text-decoration-none dropdown-toggle" href="#" role="link" id="dropdownLink"
                        data-bs-toggle="dropdown" aria-expanded="false">
                        手配先ご住所
                        <svg xmlns="http://www.w3.org/2000/svg" width="12" height="12" fill="currentColor"
                            class="bi bi-chevron-down" viewBox="0 0 16 16">
                            <path fill-rule="evenodd"
                                d="M1.646 4.646a.5.5 0 0 1 .708 0L8 10.293l5.646-5.647a.5.5 0 0 1 .708.708l-6 6a.5.5 0 0 1-.708 0l-6-6a.5.5 0 0 1 0-.708z" />
                        </svg>
                    </a>

                    <ul class="dropdown-menu" aria-labelledby="dropdownLink">
                        <li class="item small">{{order.full_name}}様</li>
                        <li class="item small">{{order.address1}}</li>
                        <li class="item small">{{order.address2}}</li>
                        <li class="item small">{{order.post_code}}</li>
                    </ul>
                </div>

            </div>
            <div class="text-end">
                お支払い済み　計: <span class="fw-bold">¥{{ order.total_paid|intcomma }}/{{ order.total_paid|intcomma }}</span>
            </div>
        </div>
        <div class="col-md-5 col-lg-4 order-md-last p-0 order-3">
            <div class="d-grid gap-2 ">
                <button class="btn btn-warning" type="button">Problem with order</button>
                <button class="btn btn-light" type="button">Leave a review</button>
            </div>
        </div>

        <div class="col-md-7 col-lg-8 p-0">

            {% for item in order.items.all %}

            <div class="card mb-3 border-0">
                <div class="row g-0">
                    <div class="col-md-2 d-none d-md-block">
                        <img class="img-fluid" style="width:90px" src="{{item.product.image.url}}" />
                    </div>
                    <div class="col-md-10">
                        <div class="card-body p-1">
                            <a class="text-decoration-none" href="{{ item.product.get_absolute_url }}">
                                <p class="card-text small">{{item.product|title}}</p>
                            </a>
                        </div>
                    </div>
                </div>
            </div>


            {% endfor %}


        </div>

    </div>
    {% endfor %}

</div>






{% endblock %}