basket/urls.py
from django.urls import path,include
from . import views

app_name = 'basket'

urlpatterns = [
    path('',views.basket_summary,name='basket_summary'),
    path('add/',views.basket_add,name='basket_add'),
    path('delete/',views.basket_delete,name='basket_delete'),
    path('update/',views.basket_update,name='basket_update'),
]

blog/urls.py
from django.urls import path,include
from . import views

urlpatterns = [
    path('',views.index),
    path('<slug:pk>/',views.article)
]

config/urls.py
from django.contrib import admin
from django.urls import path,include
from mainapp import views
from django.conf import settings
from django.conf.urls.static import static


handler500 = views.my_customized_server_error

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('mainapp.urls')),
    path('blog/',include('blog.urls')),
    path('store/',include('store.urls',namespace='store')),
    path('basket/',include('basket.urls',namespace='basket')),
    path('payment/',include('payment.urls',namespace='payment')),
    path('orders/',include('orders.urls',namespace='orders')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)

payment/urls.py
from django.urls import path
from payment import views


app_name = 'payment'

urlpatterns = [
    path('basket_view/', views.basket_view,name='basket_view'),
    path('create_stripe_payment/', views.create_stripe_payment, name='create_stripe_payment'),
    path('stripe_confirm/', views.stripe_confirm, name='stripe_confirm'),
    
    path('upgrade/', views.upgrade, name='upgrade'),
    path('payment_method/', views.payment_method, name='payment_method'),
    path('card/', views.card, name='card'),
    
    path('checkout_complete/', views.checkout_complete, name='checkout_complete'),
    path('order_placed/', views.order_placed, name='order_placed'),
    path('error/', views.Error.as_view(), name='error'),
    path('webhook/', views.stripe_webhook),
]

store/urls.py
from django.urls import path

from . import views

app_name = 'store'

urlpatterns = [
    
    path('', views.product_all, name='product_all'),
    path('<slug:slug>/', views.product_single,name='product_single'),
    path('search/<slug:category_slug>/', views.category_list,name='category_list'),
    
]

store/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.urls import reverse

class ProductManager(models.Manager):
    def get_queryset(self):
        return super(ProductManager, self).get_queryset().filter(is_active=True)

# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=255,db_index=True)
    slug = models.SlugField(max_length=255, unique=True)
    
    class Meta:
        verbose_name_plural = 'categories'
        
    def __str__(self):
        return self.name
    
class Product(models.Model):
    category = models.ForeignKey(Category, related_name='product', on_delete=models.CASCADE)
    created_by = models.ForeignKey(get_user_model(), on_delete=models.CASCADE, related_name='product_creator')
    title = models.CharField(max_length=255)
    author = models.CharField(max_length=255, default='admin')
    description = models.TextField(blank=True)
    image = models.ImageField(upload_to='store/images/',default='store/images/default.jpg')
    slug = models.SlugField(max_length=255)
    price = models.IntegerField()
    in_stock = models.BooleanField(default=True)
    is_active = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    
    class Meta:
        verbose_name_plural = 'Products'
        ordering = ('-created',)
        
    def get_absolute_url(self):
        return reverse("store:product_single",args=[self.slug])
    
        
    def __str__(self):
        return self.title

basket/views.py
from django.shortcuts import render,get_object_or_404
from django.http import JsonResponse
from store.models import Product
from .basket import Basket
import json

def basket_summary(req):
    context = {'basket':Basket(req)}
    return render(req, 'store/basket/summary.html',context)

def basket_add(req):
    basket = Basket(req)
    if req.POST.get('action') == 'post':
        product_id = int(req.POST.get('productid'))
      
        qty = int(req.POST.get('productqty'))
        product = Product.objects.get(id=product_id)
        
        is_added = basket.add(product=product, qty=qty)
        if is_added:
            msg = 'カートに商品を追加しました。'
        else:
            msg = '同じ商品がすでに追加されています。'
       
        context ={'qty':basket.__len__(), 
                  'message':msg,
                  'is_added':is_added}
        # basketqty=basket.__len__()
        return JsonResponse((context))
    
def basket_delete(req):
    
    basket = Basket(req)
    if req.POST.get('action') == 'post':
        product_id = int(req.POST.get('productid'))
        basket.delete(product=product_id)
        
        context = {'qty':basket.__len__(),
                   'subtotal':basket.get_total_price()
                }
        return JsonResponse((context))
    
def basket_update(req):
    basket = Basket(req)
    if req.POST.get('action') == 'post':
        product_id = int(req.POST.get('productid'))
        qty = int(req.POST.get('productqty'))
        basket.update(product=product_id, qty=qty)
        context = {'qty':basket.__len__(),
                   'subtotal':basket.get_total_price(),
                   'message':'製品の数量が変更されました。'
                }
        return JsonResponse((context))

store/views.py
from django.shortcuts import get_object_or_404, render

from .models import  Category, Product

def categories(req):
    return {
        'categories': Category.objects.all()
    }
    
def category_list(req, category_slug):
    category = get_object_or_404(Category,slug=category_slug)
    products = Product.objects.filter(category=category)
    
    context = {'category': category, 
               'products':products}
    return render(req,'store/products/category.html',context)

def product_all(req):
    products = Product.objects.all()
    categories = Category.objects.all()
    context = {'products': products,'categories':categories}
    return render(req, 'store/home.html', context)

def product_single(req,slug):
    product = get_object_or_404(Product,slug=slug, in_stock=True)
    context = {'product': product}
    return render(req,'store/products/single.html',context)

templates/store/basket/summary.html
{% extends '../../mainapp/base_index.html' %}{% load static %}
{% load humanize %}
{% block content%}
<div class="page-top"></div>

<div class="container mt-3" style="max-width: 1000px">
    <div class="basket-title">
        <h1 class="page-top-title ps-5 pt-3">買い物かご</h1>
        <p class="px-5 text-white">中身をご確認ください。</p>
    </div>

    {% for item in basket %}
    {% with product=item.product %}
    <div data-index={{product.id}} class="row mb-4 product-item">
        <div class="summary-item card-effect text-center">
            <img src="{{product.image.url}}" alt="Responsice image" class="img-fluid">
            <h5 class="mt-2"><a href="{{ product.get_absolute_url }}"
                    class="text-dark text-decoration-none">{{product.title}}</a></h5>
            <div class="border">
                <div class="col border-bottom">
                    <div class="row p-3">
                        <div class="col-12 text-enter">
                            <span class="h6 fw-bold">¥{{product.price|intcomma}}</span>
                        </div>
                    </div>
                </div>
                <div class="col">
                    <div class="row p-3">
                        <div class="col-12">
                            <label for="select">Qty</label>
                            <select id="select{{product.id}}">
                                <option selected>{{item.qty}}</option>
                                <option value="">1</option>
                                <option value="">2</option>
                                <option value="">3</option>
                                <option value="">4</option>
                            </select>
                            <button type="button" id="update-button" data-index="{{product.id}}"
                                class="btn btn-outline-secondary btn-sm update-button">更新</button>
                            <button type="button" id="delete-button" data-index="{{product.id}}"
                                class="btn btn-outline-danger btn-sm delete-button">削除</button>

                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
    {% endwith %}
    {% endfor %}

    <div class="col-12 text-end">
        <div class="h6 fw-bold">お支払い額　合計：¥<div id="subtotal" class="d-inline-flex">
            </div><input type="hidden" id='id_subtotal' value="{{basket.get_total_price}}" />
        </div>
    </div>
    <form action="{%url 'payment:create_stripe_payment' %}" method="post">
        {% csrf_token %}
        <div class=" row my-3 mx-2" id="paytypes">
            <h4 class="mb-3">お支払い方法</h4>
            <div>
                <input type="radio" id="pay_type" name="paytype" value="default" checked>
                <label for="prepay">通常支払い（20％前払い、サービス後残額支払い 現金可）</label>
            </div>

            <div>
                <input type="radio" id="pay_type" name="paytype" value="pre">
                <label for="prepay">一括前払い（30％割引）</label>
            </div>
        </div>

        <div class="row button-container" id="pay_selection">
            <div class="row  col-md-12">
                <button type="submit" class="pay col-md-3 card-effect text-center">
                    <h3>クレジットカード</h3>
                    <div class="row ">
                        <div class="pay-img col-md-12">
                            <img class="credit-card" src="{% static 'payment/credit-card-regular-168.png'%}" alt="">
                        </div>
                    </div>
                </button>


                <button type="submit" class="pay col-md-3 card-effect text-center">

                    <h3>Apple Pay</h3>

                    <div class="row apple">
                        <div class="pay-img col-md-12">
                            <img class="apple" src="{% static 'payment/Apple_Pay.svg'%}" alt="apple_pay">
                        </div>

                    </div>

                </button>


                <button type="submit" class="pay col-md-3 card-effect text-center">

                    <h3>Google Pay</h3>

                    <div class="row apple">
                        <div class="pay-img col-md-12">
                            <img class="google" src="{% static 'payment/GPay_Acceptance_Mark_800.png'%}"
                                alt="google_pay">
                        </div>

                    </div>

                </button>



                <button type="submit" class="pay col-md-3 card-effect text-center">

                    <h3>PayPay</h3>

                    <div class="row apple">
                        <div class="pay-img col-md-12">
                            <img class="paypay" src="{% static 'payment/img_logo_2.jpg'%}" alt="pay_pay">
                        </div>

                    </div>

                </button>
            </div>




        </div>

    </form>

</div>



<hr class="my-4">



</div>


</div>


<script>
    let basketTotal = parseInt(document.getElementById('id_subtotal').value);
    let pay_types = document.querySelectorAll('#pay_type');
    window.onload = function () {

        paySelectionDisplay();

        console.log(typeof (subtotal))

        if (subtotal != 0) {
            pay_types.forEach((element) => {
                PayType(element);

                element.addEventListener('click', function () {
                    PayType(element);
                })


            })
        }


    }
    document.getElementById('id_subtotal').addEventListener('change', (e) => {
        if (subtotal != 0) {
            pay_types.forEach((element) => {
                PayType(element);
            })
        }
    })

    function PayType(element) {
        if (element.checked) {
            if (element.value === 'default') {
                document.getElementById('subtotal').textContent = (basketTotal * 0.2).toLocaleString() + "/" + basketTotal.toLocaleString()
            } else if (element.value === 'pre') {
                document.getElementById("subtotal").textContent = (basketTotal * 0.7).toLocaleString() + "(30%割引)"
            }
        }

    }




    $(document).on('click', '.delete-button', function (e) {
        e.preventDefault();
        let prodid = $(this).data('index');
        $.ajax({
            type: 'POST',
            url: '{% url "basket:basket_delete" %}',
            data: {
                productid: $(this).data('index'),
                csrfmiddlewaretoken: "{{csrf_token}}",
                action: 'post'
            },
            success: function (json) {
                $('.product-item[data-index="' + prodid + '"]').remove();
                document.getElementById("subtotal").innerHTML = json.subtotal;
                document.getElementById("basket-qty").innerHTML = json.qty;
                paySelectionDisplay();
            },
            error: function (xhr, errmsg, err) { }
        });


    })

    $(document).on('click', '.update-button', function (e) {
        e.preventDefault();
        let prodid = $(this).data('index');
        console.log(prodid)
        $.ajax({
            type: 'POST',
            url: '{% url "basket:basket_update" %}',
            data: {
                productid: $(this).data('index'),
                productqty: $('#select' + prodid + ' option:selected').text(),
                csrfmiddlewaretoken: "{{csrf_token}}",
                action: 'post'
            },
            success: function (json) {
                console.log('update op succeeded')
                document.getElementById('basket-qty').innerHTML = json.qty
                document.getElementById('subtotal').innerHTML = json.subtotal
                _showAlert(json.message, prodid)
            },
            error: function (xhr, errmsg, err) { }
        });


    })

    function _showAlert(msg, prodid) {
        var $alert = $('<div>').prependTo($('.product-item[data-index="' + prodid + '"]')).addClass('alert rounded-0 alert alert-success');

        $alert.hide().text(msg).fadeIn(3000, function () {
            $alert.fadeOut(3000, function () {
                $alert.remove();

            });
        });

    }

    function paySelectionDisplay() {
        let paySelection = document.getElementById('pay_selection');
        let paytypes = document.getElementById('paytypes')

        if (basketTotal === 0) {
            document.getElementById('subtotal').textContent = '0';
            paySelection.style.display = 'none';
            paytypes.style.display = 'none';
        } else {
            paySelection.style.display = '';
            paytypes.style.display = '';
        }
    }



</script>

{%endblock%}