blog/urls.py
from django.urls import path,include
from . import views

urlpatterns = [
    path('',views.index),
    path('<slug:pk>/',views.article)
]

config/urls.py
from django.contrib import admin
from django.urls import path,include
from mainapp import views
from django.conf import settings
from django.conf.urls.static import static


handler500 = views.my_customized_server_error

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('mainapp.urls')),
    path('blog/',include('blog.urls')),
    path('store/',include('store.urls',namespace='store')),
    path('basket/',include('basket.urls',namespace='basket')),
    path('payment/',include('payment.urls',namespace='payment')),
    path('orders/',include('orders.urls',namespace='orders')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)

mainapp/urls.py
from django.urls import path,include
from . import views
from django.contrib import admin
from django.urls import path,include
from mainapp import views
from django.contrib.auth.views import LogoutView
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView

from mainapp.forms import (PwdResetConfirmForm, PwdResetForm)

app_name = 'mainapp'

urlpatterns = [
    path('',views.index),
    path('login/', views.Login.as_view()),
    path('logout/', LogoutView.as_view()),
    path('signup/', views.signup),
    path('activate/<slug:uidb64>/<slug:token>', views.activate,name='activate'),
    #reset password
    path('password_reset/', auth_views.PasswordResetView.as_view(template_name="mainapp/user/password_reset_form.html",
                                                                 success_url='password_reset_email_confirm',
                                                                 email_template_name='mainapp/user/password_reset_email.html',
                                                                 form_class=PwdResetForm), name='pwdreset'),
    path('password_reset_confirm/<uidb64>/<token>', auth_views.PasswordResetConfirmView.as_view(template_name='mainapp/user/password_reset_confirm.html',
                                                                                                success_url='/password_reset_complete', 
                                                                                                form_class=PwdResetConfirmForm),
         name="password_reset_confirm"),
    path('password_reset/password_reset_email_confirm/',
         TemplateView.as_view(template_name="mainapp/user/reset_status.html"), name='password_reset_done'),
    path('password_reset_complete/',
         TemplateView.as_view(template_name="mainapp/user/reset_status.html"), name='password_reset_complete'),
    path('delete_user/',views.delete_user, name='delete_user'),
    path('delete_confirmation/',views.delete_confirmation,name='delete_confirmation'),
    path('delete_cancel/',views.delete_cancel,name='delete_cancel'),
    path('account/', views.account, name='account'),
    path('account_update/', views.account_update, name='account_update'),
    path('dashboard/',views.dashboard,name='dashboard'),
    path('contact/', views.contact,name='contact'),
    path('privacy/', views.privacy,name='privacy'),
    path('quotation/', views.quotation, name='quotation'),

]

orders/urls.py
from django.urls import path

from . import views

app_name = 'orders'

urlpatterns = [
    path('add/', views.add, name='add'),
    path('test/',views.test,name='test'),
]

payment/urls.py
from django.urls import path
from payment import views


app_name = 'payment'

urlpatterns = [
    path('basket_view/', views.basket_view,name='basket_view'),
    path('create_stripe_payment/', views.create_stripe_payment, name='create_stripe_payment'),
    path('stripe_confirm/', views.stripe_confirm, name='stripe_confirm'),
    
    path('upgrade/', views.upgrade, name='upgrade'),
    path('payment_method/', views.payment_method, name='payment_method'),
    path('card/', views.card, name='card'),
    
    path('checkout_complete/', views.checkout_complete, name='checkout_complete'),
    path('order_placed/', views.order_placed, name='order_placed'),
    path('error/', views.Error.as_view(), name='error'),
    path('webhook/', views.stripe_webhook),
]

payment/forms.py
from django import forms
from orders.models import Order

class PaymentForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ('user','full_name', 'address1','address2','post_code')

payment/views.py
from django.shortcuts import render,redirect
from django.utils.decorators import method_decorator
from django.views.decorators.csrf import csrf_exempt
from django.views.decorators.http import require_POST
from django.http import JsonResponse,HttpResponse
from mainapp.models.user_models import User
from django.contrib.auth.decorators import login_required
from django.core.mail import send_mail
from django.views.generic import View
from django.views.generic.base import TemplateView
from orders.views import payment_confirmation

from basket.basket import Basket
import os,json
import stripe

def order_placed(request):
    basket = Basket(request)
    basket.clear()
    return render(request, 'payment/checkout_complete.html')


class Error(TemplateView):
    template_name = 'payment/error.html'

@login_required
def basket_view(request): 
    
    context={}
    return render(request,'payment/checkout_form.html',context)

    
@require_POST
@login_required
def create_stripe_payment(request):
    stripe.api_key = os.environ.get('STRIPE_SECRET_KEY')
    basket = Basket(request)
    total = int(basket.get_total_price())
    pre_fee = int(total*0.2)
    post_amount = total-pre_fee
    discount = []
    if request.POST.get('paytype') == 'default':
        amount = int(total * 0.2)
        amount_text = '¥{:,}(20%前払い)'.format(amount,total)
        discount_plan = {'type':'前払い　20%','price':'{:,}'.format(int(total * 0.2))}
        discount.append(discount_plan)
    elif request.POST.get('paytype')=='pre':
        amount = int(total * 0.7)
        amount_text = '¥{:,}'.format(amount)
        discount_plan = {'type':'一括前払い特典　30%割引','price':'-{:,}'.format(int(total * 0.3))}
        discount.append(discount_plan)
    try:
       
        payment_intent = stripe.PaymentIntent.create(
            amount=amount,
            currency='jpy',
            metadata={
                'userid':request.user.id,
            },
            # automatic_payment_methods={
            #     'enabled': True,
            # },
        )
        
        context={'client_secret':payment_intent.client_secret,
                 'amount':amount_text,
                 'discount':discount,
                 'payment_intent_id':payment_intent.id,
                 'payment_method_id':payment_intent.payment_method,
                 'STRIPE_PUBLISHED_KEY':os.environ['STRIPE_PUBLISHED_KEY'],
                 'customer_email':request.user.email}
        return render(request,'payment/checkout_form.html',context)
    except Exception as e:
        return JsonResponse(error=str(e))

@login_required
def stripe_confirm(request):
    context={}
    context['email']=request.user.email
    return render(request, 'payment/checkout_complete.html',context)

@login_required
def checkout_complete(request):
    
    context={"email":request.user.email}
    return render(request,'payment/checkout_complete.html',context)


@csrf_exempt
def stripe_webhook(request):
    payload = request.body
    event = None
    stripe.api_key = os.environ.get('STRIPE_SECRET_KEY')
    try:
        event = stripe.Event.construct_from(
            json.loads(payload), stripe.api_key
        )
    except ValueError as e:
        print(e)
        return HttpResponse(status=400)

    # Handle the event
    if event.type == 'payment_intent.succeeded':
        payment_confirmation(event.data.object.client_secret)

    else:
        print('Unhandled event type {}'.format(event.type))

    return HttpResponse(status=200)


@login_required
def upgrade(request):
    
    context={}
    return render(request,'payment/upgrade.html',context)

@login_required
def payment_method(request):
    stripe.api_key = os.environ.get('STRIPE_SECRET_KEY')
    basket = Basket(request)
    total = int(basket.get_total_price())
    payment_method ='card'
    context = {}
    payment_intent = stripe.PaymentIntent.create(
        amount = total,
        currency='jpy',
        payment_method_types = ['card']
    )
    
    if payment_method == 'card':
        context['client_secret'] = payment_intent.client_secret
        context['payment_intent_id'] = payment_intent.id
        context['STRIPE_PUBLISHED_KEY'] = os.environ['STRIPE_PUBLISHED_KEY']
        context['stripe_plan_id']=os.environ['STRIPE_PRODUCT_ID']
        context['customer_email']=request.user.email
        return render(request, 'payment/card.html',context)

@require_POST
@login_required
def payment_method1(request):
    stripe.api_key = os.environ.get('STRIPE_SECRET_KEY')
    plan = request.POST.get('plan', 'd')
    payment_method = request.POST.get('payment_method','card')
    amount = request.POST.get('amount')
    print(amount)
    context = {}
    payment_intent = stripe.PaymentIntent.create(
        amount = amount,
        currency='jpy',
        payment_method_types = ['card']
    )
    
    if payment_method == 'card':
        context['client_secret'] = payment_intent.client_secret
        context['payment_intent_id'] = payment_intent.id
        context['STRIPE_PUBLISHED_KEY'] = os.environ['STRIPE_PUBLISHED_KEY']
        context['stripe_plan_id']=os.environ['STRIPE_PRODUCT_ID']
        context['customer_email']=request.user.email
        return render(request, 'payment/card.html',context)
    
@login_required
def card(request):
    stripe.api_key = os.environ.get('STRIPE_SECRET_KEY')
    payment_intent_id = request.POST['payment_intent_id']
    payment_method_id = request.POST['payment_method_id']
    stripe_plan_id = request.POST['stripe_plan_id']
    automatic = 'on'
    if automatic == 'on':
       customer = stripe.Customer.create(
           email = request.user.email,
           payment_method=payment_method_id,
           invoice_settings={
               'default_payment_method': payment_method_id
           }
       )
       
       stripe.Subscription.create(
           customer=customer.id,
           items=[
               {  
                   'plan': stripe_plan_id
               }
           ]
       )
    else:
        stripe.PaymentIntent.modify(
            payment_intent_id,
            payment_method=payment_method_id
        )
    
    stripe.PaymentIntent.confirm(
       payment_intent_id
    )
    context={}
    return render(request,'payment/thankyou.html',context)

templates/payment/base_checkout.html
<!DOCTYPE html>
<html lang="jp">
{% load static %}

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta name="description" content="" />
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors" />
    <meta name="generator" content="Hugo 0.83.1" />
    <meta name="description" content="A demo of a payment on Stripe" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>Tottofare</title>


    <script src="https://code.jquery.com/jquery-3.6.3.min.js"
        integrity="sha256-pvPw+upLPUjgMXY0G+8O0xUf+/Im1MZjXxxgOcBQBXU=" crossorigin="anonymous"></script>


    <!-- Bootstrap core CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous" />
    <link href="https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css" rel="stylesheet" />


    <!-- Custom styles for this template -->
    <!-- <link href="{% static 'mainapp/styles/style.css' %}" rel="stylesheet" /> -->
    <script src="https://kit.fontawesome.com/71c00e5ffa.js" crossorigin="anonymous"></script>
</head>






<!-- Add your site or application content here -->


{% block content %}
{%endblock %}

<script src="https://cdn.jsdelivr.net/npm/fetch-jsonp@1.1.3/build/fetch-jsonp.min.js"></script>
<script type="module" src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js"></script>
<script nomodule src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.js"></script>




</html>

templates/payment/cancel.html
{% extends 'mainapp/base_index.html' %} {% block content %}

<head>
  <title>Thanks for your order!</title>
</head>
<div class="wrapper">
  <h1>ご購入処理が失敗しました!</h1>
  <p>
    入力項目、お支払い方法に問題がないかご確認ください!
    ご不明点等ございましたら下記の連絡先まで。
    <a href="mailto:orders@example.com">orders@example.com</a>.
  </p>
</div>

{%endblock%}

templates/payment/card.html
{% extends 'mainapp/base_index.html' %} {% load static %}

{% block extra_js %}

{% endblock extra_js %}

{% block extra_css %}
{% endblock extra_css %}

{% block content %}
<div class="page-top"></div>
<div class="row py-3">
    <div class="col-lg-12 col-md-12">
        <div class="container">
            <form action="{%url 'payment:card' %}" method="post" id="payment-form">
                {% csrf_token %}
                <div id="card-element">
                    <!-- Elements will create input elements here -->
                </div>
                <div id="card-errors" role="alert">
                    <!-- Elements will create input elements here -->
                </div>
                <input type="hidden" name="payment_intent_id" value="{{payment_intent_id}}" />
                <input type="hidden" name="stripe_plan_id" value="{{stripe_plan_id}" />
                <button class="btn btn-custom" id="submit-button" data-secret="{{client_secret}}">支払う</button>
            </form>
        </div>
    </div>
</div>
<script src="https://js.stripe.com/v3/"></script>
<script src="{% static 'payment/js/card.js' %}"></script>
<script>
    card('{{STRIPE_PUBLISHED_KEY}}', '{{customer_email}}')
</script>
{% endblock %}

templates/payment/checkout.html
{% extends 'mainapp/base_index.html' %}{% load static %}
{% load humanize %}
{% block extra_js %}
<link rel="stylesheet" href="{% static 'payment/styles/checkout.css' %}" />
<link rel="stylesheet" href="{% static 'payment/styles/base.css' %}" />

{% endblock extra_js %} {% block extra_css %} {% endblock extra_css %}
{% block content %}
<div class="page-top"></div>
<div class="container">
  <h1 class="page-title">支払い画面</h1>

  <h4>カード情報入力</h4>
  <!-- Display a payment form -->
  <!--Example 2-->
  <div class="cell example example2" id="example-2">
    <form class="payment-form" id="payment-form">
      {% csrf_token %}
      <label for="card-element">Credit or debit card</label>
      <div id="card-element" class="form-control form-control-payment">
        <!-- Payment elements will appear here -->
      </div>
      <hr class="my-4">
      <div class="col-md-12 d-grid mt-4">
        <button type="submit" class="btn btn-custom" id="submit"
          data-secret="{{client_secret}}">¥{{basket.get_total_price|intcomma}}
          の支払い</button>
      </div>

      <div class="error" id="card-errors" role="alert"></div>
    </form>

  </div>



</div>
<script src="https://js.stripe.com/v3/"></script>

<script src="{% static 'payment/js/index.js' %}" data-rel-js></script>
<!-- <script src="{% static 'payment/js/card.js' %}" data-rel-js></script> -->

{% endblock %}

templates/payment/checkout_complete.html
{% extends 'mainapp/base_index.html' %} {% block content %} {% load static %}
<div class="page-top"></div>
<div class="container">
    <h2>支払い完了しました。お買い上げありがとうございました。</h2>
    <p>{{user.email}}をご確認ください。迷惑メールフォルダに入っている場合がありますので、ご確認ください。</p>
    <a href="{% url 'mainapp:dashboard'%}">注文履歴を見る</a>
</div>


{% endblock %}

templates/payment/checkout_form.html
{% extends 'mainapp/base_index.html' %} {% block content %} {% load static %}
{% load humanize %}
<link rel="stylesheet" href="{% static 'payment/styles/checkout.css' %}" />

<body class="bg-light">
  <div class="page-top"></div>
  <div class="container mb-4">

    <div class="py-5 text-center">
      <h1 class="page-title">お支払いページ</h1>
      <input type='hidden' id="userid" value="{{user.id}}" />
      <p class="lead">以下に必要項目をご入力ください。</p>
    </div>

    <div class="row g-5">
      <div class="col-md-5 col-lg-4 order-md-last">
        <h4 class="d-flex justify-content-between align-items-center mb-3">
          <span class="text-info">買い物かご</span>
          {% with total_qty=basket|length %}
          <span id="basket-qty" class="badge bg-info rounded-pill">
            {% if total_qty > 0 %}
            {{total_qty}}
            {% else %}
            0
            {% endif %}
          </span>
          {% endwith %}
        </h4>
        <ul class="list-group mb-3">

          {% for item in basket %}
          {% with product=item.product %}
          <li class="list-group-item d-flex justify-content-between lh-sm">
            <div>
              <h6 class="my-0">{{product.title}}</h6>

            </div>
            <span class="text-muted">¥{{product.price|intcomma}}</span>
          </li>
          {% endwith %}
          {% endfor %}
          <li class="list-group-item d-flex justify-content-between">
            <span>計</span>
            <strong>¥{{basket.get_total_price|intcomma}}</strong>
          </li>
          {% if discount|length > 0 %}
          {% for item in discount %}
          <li class="list-group-item d-flex justify-content-between bg-light">
            <div class="text-success">
              <h6 class="my-0">備考</h6>
              <small>{{item.type}}</small>
            </div>
            <span class="text-success">¥{{item.price}}</span>
          </li>
          {% endfor %}
          {% endif %}
          <li class="list-group-item d-flex justify-content-between">
            <span>お支払い額</span>
            <strong>{{amount}}</strong>
          </li>
        </ul>
      </div>
      <div class="col-md-7 col-lg-8">
        <h4 class="mb-3">お支払い情報</h4>
        <form class="needs-validation" id="payment-form" action="{%url 'orders:add' %}">
          {% csrf_token %}
          <div class="row g-3">
            <div class="col-sm-12">
              <label for="fullName" class="form-label">お名前</label>
              <input type="text" class="form-control" id="fullName" name="fullname" placeholder=""
                value="{{user.profile.username}}" required>
              <div class="invalid-feedback">
                お名前をご入力ください。
              </div>
            </div>


            <div class="col-12">
              <label for="email" class="form-label">Email</label>
              <input type="email" class="form-control" id="email" name="email" placeholder="you@example.com"
                value="{{user.email}}" required>
              <div class="invalid-feedback">
                emailをご入力ください。
              </div>
            </div>

            <div class="col-md-4">
              <label for="zip" class="form-label">郵便番号</label>
              <input type="text" class="form-control" id="zipcode" name="zipcode" value="{{ user.profile.zipcode}}"
                required>
              <div class="invalid-feedback">
                郵便番号が必要です。
              </div>
            </div>

            <div class="col-md-4 d-grid">
              <label for="zip" class="form-label">住所→郵便番号</label>
              <button class="btn btn-info" id="search" type="button">郵便番号検索</button>
              <p id="error"></p>
            </div>

            <div class="col-md-4">
              <label for="state" class="form-label">都道府県</label>
              <input type="hidden" id="address1" name="address1" value="{{user.profile.prefecture}}"
                placeholder="例）大阪府">
              <select class="form-select" name="pref_name" id="pref_name" required>
                <option value="" selected>選択してください</option>
                <option value="北海道">北海道</option>
                <option value="青森県">青森県</option>
                <option value="岩手県">岩手県</option>
                <option value="宮城県">宮城県</option>
                <option value="秋田県">秋田県</option>
                <option value="山形県">山形県</option>
                <option value="福島県">福島県</option>
                <option value="茨城県">茨城県</option>
                <option value="栃木県">栃木県</option>
                <option value="群馬県">群馬県</option>
                <option value="埼玉県">埼玉県</option>
                <option value="千葉県">千葉県</option>
                <option value="東京都">東京都</option>
                <option value="神奈川県">神奈川県</option>
                <option value="新潟県">新潟県</option>
                <option value="富山県">富山県</option>
                <option value="石川県">石川県</option>
                <option value="福井県">福井県</option>
                <option value="山梨県">山梨県</option>
                <option value="長野県">長野県</option>
                <option value="岐阜県">岐阜県</option>
                <option value="静岡県">静岡県</option>
                <option value="愛知県">愛知県</option>
                <option value="三重県">三重県</option>
                <option value="滋賀県">滋賀県</option>
                <option value="京都府">京都府</option>
                <option value="大阪府">大阪府</option>
                <option value="兵庫県">兵庫県</option>
                <option value="奈良県">奈良県</option>
                <option value="和歌山県">和歌山県</option>
                <option value="鳥取県">鳥取県</option>
                <option value="島根県">島根県</option>
                <option value="岡山県">岡山県</option>
                <option value="広島県">広島県</option>
                <option value="山口県">山口県</option>
                <option value="徳島県">徳島県</option>
                <option value="香川県">香川県</option>
                <option value="愛媛県">愛媛県</option>
                <option value="高知県">高知県</option>
                <option value="福岡県">福岡県</option>
                <option value="佐賀県">佐賀県</option>
                <option value="長崎県">長崎県</option>
                <option value="熊本県">熊本県</option>
                <option value="大分県">大分県</option>
                <option value="宮崎県">宮崎県</option>
                <option value="鹿児島県">鹿児島県</option>
                <option value="沖縄県">沖縄県</option>
              </select>
              <div class="invalid-feedback">
                都道府県を選択してください。
              </div>
            </div>






            <div class="col-12">
              <label for="address" class="form-label">市区町村</label>
              <input type="text" class="form-control" id="address2" name="address2" value="{{ user.profile.city }}"
                required>
              <div class="invalid-feedback">
                住所を入力してください。
              </div>
            </div>

            <div class="col-12">
              <label for="address2" class="form-label">町域 </label>
              <input type="text" class="form-control" id="address3" name="address3" placeholder=""
                value="{{ user.profile.address1}}" required>
              <div class="invalid-feedback">
                町域を入力してください。
              </div>
            </div>

            <div class="col-12">
              <label for="address2" class="form-label">建物名・部屋番号<span class="text-muted">(Optional)</span></label>
              <input type="text" class="form-control" id="address4" name="address4" placeholder=""
                value="{{ user.profile.address2}}">
            </div>
          </div>

          <hr class="my-4">

          <div class="form-check">
            <input type="checkbox" class="form-check-input" id="save-info">
            <label class="form-check-label" for="save-info">アカウント情報に保存する</label>
          </div>

          <hr class="my-4">
          <h4>カード情報入力</h4>
          <label for="card-element">Credit or debit card</label>
          <div id="card-errors"></div>
          <div id="card-element" class="form-control form-control-payment">
            <!-- Payment elements will appear here -->
          </div>
          <hr class="my-4">
          <input type="hidden" id="payment_intent_id" name="payment_intent_id" value="{{payment_intent_id}}" />
          <input type="hidden" name="stripe_plan_id" value="{{stripe_plan_id}" />
          <button id="submit" class="btn btn-custom w-100 fw-bold" data-secret="{{ client_secret }}">お支払い</button>
        </form>
      </div>
    </div>
  </div>

  <script src="{% static 'mainapp/js/form-validation.js' %}"></script>
  <script src="{% static 'mainapp/js/search_address.js' %}"></script>
  <script src="https://polyfill.io/v3/polyfill.min.js?version=3.52.1&features=fetch"></script>

  <script>
    let CSRF_TOKEN = '{{ csrf_token}}';
    let userid = document.getElementById("userid").value;
    let payment_intent_id = document.getElementById("payment_intent_id").value;
  </script>
  <script src="https://js.stripe.com/v3/"></script>
  <script src="{% static 'payment/js/index.js' %}" data-rel-js></script>
  <script>card('{{STRIPE_PUBLISHED_KEY}}', '{{customer_email}}')</script>
</body>


{% endblock %}

templates/payment/error.html
{%extends "base.html"%}
{%block content%}
  <div class="jumbotron">
      <h1 class="">403 Access Forbidden!</h1>
  </div>

{%endblock%}

templates/payment/thankyou.html
{% extends 'mainapp/base_index.html' %} {% block content %} {% load static %}
{% load humanize %}



<div class="page-top"></div>

thank you!
{% endblock %}

templates/payment/upgrade.html
{% extends 'mainapp/base_index.html' %} {% block content %} {% load static %}
{% load humanize %}

<div class="page-top"></div>

<div class="row">
    <div class="col-lg-12">
        <div class="container">
            <h3>Upgrade</h3>
            <form method="post" action="{%url 'payment:payment_method' %}">
                {% csrf_token %}
                <div class="form-group">
                    <label>お支払い額</label>
                    <input type="text" id="amount" name="amount" value="2000" readonly />
                </div>

                <div class="form-group">
                    <label>プラン</label>
                    <select id="plan" name="plan">
                        <option selected value="0">選択してください</option>
                        <option value="1">前払い20％　残金は後日お支払い</option>
                        <option value="2">一括前払い 15%off</option>
                    </select>
                </div>

                <div class="form-group">
                    <label>お支払い方法</label>
                    <label><input type="radio" name="payment_method" value="card" checked>クレジットカード</label>
                    <label><input type="radio" name="payment_method" value="paypal">PayPal</label>
                </div>
                <button type="submit" class="btn btn-custom mb-2">Check</button>
            </form>
        </div>
    </div>
</div>

{% endblock %}