basket/urls.py
from django.urls import path,include
from . import views

app_name = 'basket'

urlpatterns = [
    path('',views.basket_summary,name='basket_summary'),
    path('add/',views.basket_add,name='basket_add'),
    path('delete/',views.basket_delete,name='basket_delete'),
    path('update/',views.basket_update,name='basket_update'),
]

blog/urls.py
from django.urls import path,include
from . import views

urlpatterns = [
    path('',views.index),
    path('<slug:pk>/',views.article)
]

config/urls.py
from django.contrib import admin
from django.urls import path,include
from mainapp import views
from django.conf import settings
from django.conf.urls.static import static


handler500 = views.my_customized_server_error

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('mainapp.urls')),
    path('blog/',include('blog.urls')),
    path('store/',include('store.urls',namespace='store')),
    path('basket/',include('basket.urls',namespace='basket')),
    path('payment/',include('payment.urls',namespace='payment')),
    path('orders/',include('orders.urls',namespace='orders')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)

mainapp/urls.py
from django.urls import path,include
from . import views
from django.contrib import admin
from django.urls import path,include
from mainapp import views
from django.contrib.auth.views import LogoutView
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView

from mainapp.forms import (PwdResetConfirmForm, PwdResetForm)

app_name = 'mainapp'

urlpatterns = [
    path('',views.index),
    path('login/', views.Login.as_view()),
    path('logout/', LogoutView.as_view()),
    path('signup/', views.signup),
    path('activate/<slug:uidb64>/<slug:token>', views.activate,name='activate'),
    #reset password
    path('password_reset/', auth_views.PasswordResetView.as_view(template_name="mainapp/user/password_reset_form.html",
                                                                 success_url='password_reset_email_confirm',
                                                                 email_template_name='mainapp/user/password_reset_email.html',
                                                                 form_class=PwdResetForm), name='pwdreset'),
    path('password_reset_confirm/<uidb64>/<token>', auth_views.PasswordResetConfirmView.as_view(template_name='mainapp/user/password_reset_confirm.html',
                                                                                                success_url='/password_reset_complete', 
                                                                                                form_class=PwdResetConfirmForm),
         name="password_reset_confirm"),
    path('password_reset/password_reset_email_confirm/',
         TemplateView.as_view(template_name="mainapp/user/reset_status.html"), name='password_reset_done'),
    path('password_reset_complete/',
         TemplateView.as_view(template_name="mainapp/user/reset_status.html"), name='password_reset_complete'),
    path('delete_user/',views.delete_user, name='delete_user'),
    path('delete_confirmation/',views.delete_confirmation,name='delete_confirmation'),
    path('delete_cancel/',views.delete_cancel,name='delete_cancel'),
    path('account/', views.account, name='account'),
    path('account_update/', views.account_update, name='account_update'),
    path('dashboard/',views.dashboard,name='dashboard'),
    path('contact/', views.contact,name='contact'),
    path('privacy/', views.privacy,name='privacy'),
    path('quotation/', views.quotation, name='quotation'),

]

store/urls.py
from django.urls import path

from . import views

app_name = 'store'

urlpatterns = [
    
    path('', views.product_all, name='product_all'),
    path('<slug:slug>/', views.product_single,name='product_single'),
    path('search/<slug:category_slug>/', views.category_list,name='category_list'),
    
]

mainapp/models/account_models.py
from django.db import models
from django.contrib.auth.models import BaseUserManager

from django.contrib.auth import get_user_model
from django.core.mail import send_mail
import os



class UserManager(BaseUserManager):
    def create_user(self,email,password=None):
        if not email:
            raise ValueError('Users must have an email address')
        user = self.model(
            email=self.normalize_email(email),
        )
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self,email,password=None):
        user = self.create_user(
            email,
            password=password
        )
        user.is_admin = True
        user.is_active = True
        user.save(using=self._db)
        return user
    

mainapp/models/profile_models.py
from django.db import models
from django.contrib.auth import get_user_model

class Profile(models.Model):
    user = models.OneToOneField(get_user_model(),unique=True, on_delete=models.CASCADE, primary_key=True)
    username = models.CharField(default="",max_length=30)
    zipcode = models.CharField(default="",max_length=8)
    prefecture = models.CharField(default="",max_length=6)
    city = models.CharField(default="",max_length=100)
    address1 = models.CharField(default="",max_length=200)
    address2 = models.CharField(default="",max_length=50,null=True)
    stripe_id= models.CharField(default="",max_length=30,null=True)
    

mainapp/models/user_models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser
from .account_models import UserManager
from django.core.mail import send_mail
import os

class User(AbstractBaseUser):
    email = models.EmailField(max_length=255,unique=True)
    
    is_active = models.BooleanField(default=False)
    is_admin = models.BooleanField(default=False)
    objects = UserManager()
    
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []
    
    def __str__(self):
        return self.email
    
    def has_perm(self, prerm, obj=None):
        "Does the user have a specific permission?"
        return True
    
    def has_module_perms(self, app_label):
        "Does the user have permissions to view the app 'app_label'?"
        return True
    
    def email_user(self, subject, message):
        email_from = os.environ['EMAIL_HOST_USER']
        email_to = [self.email]
        send_mail(
            subject,
            message,
            email_from,
            email_to,
            fail_silently=False,
        )
    
    @property
    def is_staff(self):
        "Is the user a member of staff?"
        return self.is_admin
    
from django.db.models.signals import post_save
from django.dispatch import receiver

@receiver(post_save, sender=User)
def create_onetoone(sender, **kwargs):
    if kwargs['created']:
        from mainapp.models.profile_models import Profile
        
        Profile.objects.create(user=kwargs['instance'])

mainapp/forms.py
from django import forms
from django.contrib.auth.forms import (PasswordResetForm,SetPasswordForm)
from django.contrib.auth import get_user_model
from .models.profile_models import Profile
from .models.user_models import User

class UserCreationForm(forms.ModelForm):
    password = forms.CharField()
    
    class Meta:
        model = get_user_model()
        fields = ('email',)
        
    def clean_password(self):
        password =self.cleaned_data.get("password")
        return password
    
    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password"])
        if commit:
            user.save()
        return user
    
class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = (
            'username',
            'zipcode',
            'prefecture',
            'city',
            'address1',
            
            
        )
        
class PwdResetForm(PasswordResetForm):

    email = forms.EmailField(max_length=254, widget=forms.TextInput(
        attrs={'class': 'form-control mb-3', 'placeholder': 'Email', 'id': 'form-email'}))

    def clean_email(self):
        email = self.cleaned_data['email']
        u = User.objects.filter(email=email)
        if not u:
            raise forms.ValidationError(
                'そのE-mailアドレスは登録されていません。')
        return email


class PwdResetConfirmForm(SetPasswordForm):
    new_password1 = forms.CharField(
        label='新しいパスワード', widget=forms.PasswordInput(
            attrs={'class': 'form-control mb-3', 'placeholder': 'New Password', 'id': 'form-newpass'}))
    new_password2 = forms.CharField(
        label='もう一度入力してください。', widget=forms.PasswordInput(
            attrs={'class': 'form-control mb-3', 'placeholder': 'New Password', 'id': 'form-new-pass2'}))
        

mainapp/views.py
from django.shortcuts import render,redirect
from blog.models import Article
from django.contrib.auth.views import LoginView
from django.views.decorators.csrf import csrf_exempt
from django.http import  HttpResponse, JsonResponse
from django.contrib.sites.shortcuts import get_current_site
from django.template.loader import render_to_string
from django.utils.encoding import force_bytes, force_str
from django.utils.http import urlsafe_base64_decode, urlsafe_base64_encode

from .tokens import account_activation_token
from .models.user_models import User
from .models.profile_models import Profile
from mainapp.forms import UserCreationForm, ProfileForm
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth import login,logout
from django.core.mail import send_mail
from orders.views import user_orders

import os


def index(request):
    objs=Article.objects.all()
    context={
        'articles': objs
    }
    return render(request,'mainapp/index.html',context)

def signup(request):
    context={}
    if request.user.is_authenticated:
        return redirect('/')
    if request.method == 'post':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            #user.is_active = False
            user.save()
            # login(request,user)
            # messages.success(request,"登録完了！")
            current_site = get_current_site(request)
            subject = 'Tuttofareアカウントをアクティベートしてください'
            message = render_to_string('mainapp/registration/account_activation_email.html', {
                'user': user,
                'domain': current_site.domain,
                'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                'token': account_activation_token.make_token(user),
            })
            user.email_user(subject=subject, message=message)
            my_text = '新規登録が成功しました。\nアクティベーション用のリンクをご登録メールにお送りしました。\
                \n（迷惑メールフォルダに入っている可能性があります。）\
                \nregistered succesfully and activation sent'
            return HttpResponse(my_text.encode('Shift_JIS'),content_type='text/plain')
        else:
            context = {'form':form}
    return render(request,'mainapp/auth.html',context)

def activate(request,uidb64,token):
    try:
        uid = force_str(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except:
        print('uid, userが見つかりません。')
    if user is not None and account_activation_token.check_token(user,token):
        user.is_active = True
        user.save()
        login(request,user)
        return redirect('/')
    else:
        return render(request,'mainapp/registration/activation_invalid.html')
    
      
    

class Login(LoginView):
    template_name = 'mainapp/auth.html'

    def form_valid(self,form):
        messages.success(self.request, "ログイン完了！")
        return super().form_valid(form)

    def form_invalid(self, form):
        messages.error(self.request, "ログイン失敗！")
        return super().form_invalid(form)

# def logout(request):
#     context={}
#     return render(request,'mainapp/logout.html',context)

@login_required
def dashboard(request):
    context={}
    try:
        orders = user_orders(request)
        context['orders']=orders
    except:
        print('no orders')
    
   
    return render(request,'mainapp/dashboard.html',context)

@login_required
def account(request):
    print(request.user)
    profile=Profile.objects.get(user=request.user)
    
    
    if request.method == 'POST':
        form = ProfileForm(request.POST)
        print(form)
        if form.is_valid():
            profile = form.save(commit=False)
            profile.user = request.user
            profile.save()
            messages.success(request,"アカウント情報更新完了！")
            context={'profile':profile}
            return render(request,'mainapp/account.html',context)
    context={'profile':profile}
    return render(request,'mainapp/account.html',context)

@login_required
def account_update(request):
   
    print("username",request.POST.get('username'))
    user=User.objects.get(id=request.POST.get('key'))
    
    defaults={
            'username':request.POST.get('username'),
            'prefecture':request.POST.get('prefecture'),
            'city':request.POST.get('city'),
            'address1':request.POST.get('address1'),
            'address2':request.POST.get('address2'),
            'zipcode':request.POST.get('zipcode')}
    try:
        obj = Profile.objects.get(user=user)
      
        for key, value in defaults.items():
            setattr(obj, key, value)
        obj.user = user
        obj.save()
    except Profile.DoesNotExist:
        new_values = {'user': user}
        new_values.update(defaults)
        obj = Profile(**new_values)
        obj.save()
    context = {'msg':'アカウント更新完了！','profile':defaults}
    return JsonResponse((context))
    # if created:
    #     messages.success(request,"アカウント情報更新完了！")
    #     context={'message':'更新完了', 'profile':profile}
    #     return JsonResponse((context))
    

@login_required
def delete_user(request):
    context={'email':request.user.email}
    # if request.method == 'POST':
    #     redirect_url = reverse('mainapp:delete_confirmation')
    #     email=request.user.email
        
    #     params=urlencode({'email':email})
    #     url=f'{redirect_url}?{params}'
    #     return redirect(url)
    return render(request,'mainapp/user/delete_confirmation.html',context)

@login_required
def delete_confirmation(request):
    if request.method == 'POST':
        email=request.POST.get('email')
        print(email)
        user = User.objects.get(email=email)
        if user is not None:
            
            user.is_active=False
            user.delete()
            logout(request)
            
            my_text = f'{email}様のアカウントは削除されました。\nご利用いただきありがとうございました。'
            return HttpResponse(my_text.encode('Shift_JIS'),content_type='text/plain')
    
    

def delete_cancel(request):
    email = request.GET.get('email')
    return redirect('/account')

def contact(request):
    context = {}
    if request.method == 'POST':
        subject = "お問い合わせがありました。"
        message = "お問い合わせがありました。\n名前: {}\nメールアドレス: {}\n内容: {}".format(
                    request.POST.get('name'),
                    request.POST.get('email'),
                    request.POST.get('content'))        
        
        email_from = os.environ['EMAIL_HOST_USER']
        email_to = [
        os.environ['EMAIL_HOST_USER'], 
        ]
        send_mail(subject,message, email_from,email_to)
        messages.success(request,'お問い合わせいただきありがとうございました。ご入力内容が送信されました。')
    return render(request,'mainapp/contact.html',context)


def privacy(request):
    context={}
    return render(request, 'mainapp/privacy.html',context)

@csrf_exempt
def quotation(request):
    context={}
    return render(request,'mainapp/quotation.html',context)

def success(request):
    user = User.objects.get(id=request.user.id)
    context={"username": user.email}
    return render(request,'mainapp/success.html',context)

def cancel(request):
    context={}
    return render(request,'mainapp/cancel.html',context)






from django.views.decorators.csrf import requires_csrf_token
from django.http import HttpResponseServerError

@requires_csrf_token
def my_customized_server_error(request, template_name='500.html'):
    import sys
    from django.views import debug
    error_html = debug.technical_500_response(request, *sys.exc_info()).content
    return HttpResponseServerError(error_html)

templates/mainapp/snippets/comment.html
<div>
    <h3 class="h6">コメント</h3>
    <div class="list-group">

        {% for comment in comments%}
        <a href="" class="list-group-item list-group-item-action p-3 rounded-0">
            <p class="m-0"><small>{{comment.comment}}</small></p>
            <p class="m-0"><small>ユーザー：{{comment.user.profile.username}} さん</small></p>
            <p class="m-0"><small>投稿日：{{comment.created_at}}</small></p>
        </a>
        {% endfor %}
    </div>
        {% if user.is_authenticated %}
        <form method="POST" class="my-4">
        {% csrf_token %}
            <div class="mb-2">
                <label >コメント投稿</label>
                <textarea name="comment" class="rounded-0 bg-light form-control" rows="3"></textarea>
            </div>
            <div class="text-right">
                <button class="btn btn-sm btn-outline-success" type="submit">
                    コメントする
                </button>
            </div>
        </form>
        {% else %}
        <p class="my-4">
            コメントを投稿するには<a href="/login/">ログイン</a>してください。
        </p>
        {% endif %}
</div>

templates/mainapp/snippets/footer.html
<footer class="p-3 mt-4">
    <p class="float-end"><a href="/">Back to top</a></p>
    <p>&copy 2022 Tuttofare powered by tech2metail &middot; <a href="/privacy">Privacy</a> &middot; <a
            href="/contact">Contact</a></p>

</footer>

<!-- Optional JavaScript; choose one of the two! -->

<!-- Option 1: Bootstrap Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW"
    crossorigin="anonymous"></script>

<!-- Option 2: Separate Popper and Bootstrap JS -->
<!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js" integrity="sha384-q2kxQ16AaE6UbzuKqyBE9/u/KzioAlnx2maXQHiDX9d4/zp8Ok3f+M7DPm+Ib6IU" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.min.js" integrity="sha384-pQQkAEnwaBkjpqZ8RU1fF1AKtTcHJwFl3pblpTlHXybJjHpMYo79HY3hIi4NKxyj" crossorigin="anonymous"></script>
    -->

templates/mainapp/snippets/grecaptcha.html
<script src="https://www.google.com/recaptcha/api.js" async defer></script>

<div class="g-recaptcha" 
     data-sitekey="{{ grecaptcha_sitekey }}"
     data-callback="verifyCallback"></div>

<script>
    // コールバック関数
    function verifyCallback(response){
        console.log(response)
        // submit のdisabled属性を解除
        document.getElementById('submit').disabled = false;
    }
</script>

templates/mainapp/snippets/header.html
<header>
    <div class="row" id="navArea">
        <nav class="navbar navbar-expand-md navbar-light bg-dark border-bottom">
            <div class="container-fluid">
                <h2><a class="navbar-brand" href="/">Tuttofare</a></h2>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse"
                    aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarCollapse">
                    <!-- <ul class="navbar-nav me-auto mb-2 mb-md-0">
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                                data-bs-toggle="dropdown" aria-expanded="false">
                                Library
                            </a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <li><a class="dropdown-item" href="#">All</a></li>

                                <li class="selected">
                                    <a class="dropdown-item" href="#"></a>
                                </li>

                            </ul>
                        </li>
                    </ul> -->
                    <a class="nav-link" href="/">Home</a>
                    <a class="nav-link" href="/quotation">見積もり</a>
                    <a class="nav-link" href="{%url 'store:product_all' %}">Store</a>
                    {% if user.is_authenticated %}
                    <a class="nav-link account" href="{%url 'mainapp:dashboard' %}">
                        <span class="badge">ID:{{user.email}}</span>
                    </a>
                    <a type="button" role="button" href="{% url 'basket:basket_summary' %}"
                        class="basket-btn btn btn-outline-secondary">

                        {% with total_qty=basket|length %}
                        <div id="basket-qty" class="d-inline-flex">
                            {% if total_qty > 0 %}
                            {{ total_qty }}
                            {% else %}
                            0
                            {% endif %}
                        </div>
                        {% endwith %}

                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                            class="bi bi-cart3" viewBox="0 0 16 16">
                            <path
                                d="M0 1.5A.5.5 0 0 1 .5 1H2a.5.5 0 0 1 .485.379L2.89 3H14.5a.5.5 0 0 1 .49.598l-1 5a.5.5 0 0 1-.465.401l-9.397.472L4.415 11H13a.5.5 0 0 1 0 1H4a.5.5 0 0 1-.491-.408L2.01 3.607 1.61 2H.5a.5.5 0 0 1-.5-.5zM3.102 4l.84 4.479 9.144-.459L13.89 4H3.102zM5 12a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm7 0a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm-7 1a1 1 0 1 1 0 2 1 1 0 0 1 0-2zm7 0a1 1 0 1 1 0 2 1 1 0 0 1 0-2z" />
                        </svg>
                    </a>
                    <a class="nav-link" href="/logout">ログアウト</a>

                    {% else %}
                    <a class="nav-link" href="/login">ログイン</a>
                    <button class="btn ms-1"><a href="/signup">サインアップ</a></button>
                    {%endif%}

                    <a class="nav-link" href="/contact">お問い合わせ</a>

                </div>
            </div>
        </nav>
    </div>
</header>

templates/mainapp/snippets/like_count.html
<form method="POST" class="d-inline">
    {% csrf_token %}
    <input type="hidden" name="like_count" value="true">
    <button class="btn btn-sm btn-outline-warning">
        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16"
        fill="currentColor" class="bi bi-lightning-fill" viewBox="0 0 16 16">
            <path fill-rule="evenodd" d="M5.52.359A.5.5 0 0 1 6 0h4a.5.5 0 0 1 .474.658L8.694 6H12.5a.5.5 0 0 1 .395.807l-7 9a.5.5 0 0 1-.873-.454L6.823 9.5H3.5a.5.5 0 0 1-.48-.641l2.5-8.5z" />
        </svg>
        {{ article.count }} good
    </button>
</form>

templates/mainapp/snippets/messages.html
{% comment "" %} メッセージです　{% endcomment %}
{% for msg in messages %}
<nav class="messages py-2 {{ msg.tags }}">
    <div class="container">
        {{ msg }}
    </div>
</nav>
{% endfor %}

templates/mainapp/snippets/pagination.html
<nav class="blog-pagination">
        <div class="pagination">
            <span class="step-links">
                {% if page_obj.has_previous %}
                    <a href="?page=1" class="btn btn-outline-primary">&laquo; first</a>
                    <a href="?page={{ page_obj.previous_page_number }}" class="btn btn-outline-primary">previous</a>
                {% endif %}
                <span class="current">
                    Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages}}. 
                </span>
                {% if page_obj.has_next %}
                    <a href="?page={{ page_obj.next_page_number }}" class="btn btn-outline-primary">next</a>
                    <a href="?page={{ page_obj.paginator.num_pages }}" class="btn btn-outline-primary">last &raquo</a>
                {% endif %}
            </span>
        </div>
</nav>

templates/mainapp/snippets/sidebar.html
{% load static %}

    <div class="container">
    <div class="p-4 mb-3 bg-light rounded">
        <h4 class="font-italic">広告</h4>
        <p class="mb-0"></p>
    </div>

    <figure class="figure">
        <img src="{% static 'mainapp/temple.jpg' %}" class="figure-img img-fluid rouded">
        <figcaption class="figure-caption text-center font-italic small">
            
        </figcaption>
    </figure>
    <figure class="figure">
        <img src="{% static 'mainapp/sika.jpg' %}" class="figure-img img-fluid rouded">
        <figcaption class="figure-caption text-center font-italic small">
           
        </figcaption>
    </figure>
</div>

templates/mainapp/snippets/tag.html
{% for tag in article.tags.all %}
<a href="/blog/tags/{{ tag.slug }}" class="btn btn-sm btn-outline-secondary">
    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-tag-fill" viewBox="0 0 16 16">
        <path d="M2 1a1 1 0 0 0-1 1v4.586a1 1 0 0 0 .293.707l7 7a1 1 0 0 0 1.414 0l4.586-4.586a1 1 0 0 0 0-1.414l-7-7A1 1 0 0 0 6.586 
        1H2zm4 3.5a1.5 1.5 0 1 1-3 0 1.5 1.5 0 0 1 3 0z"/>
    </svg>
    {{ tag.name }}
</a>
{% endfor %}